apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.commonLabels.app }}
data:
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.configMap.data.NEXT_PUBLIC_API_BASE_URL | quote }}
  API_BASE_URL: {{ .Values.configMap.data.NEXT_PUBLIC_API_BASE_URL | quote }}
  NEXT_PUBLIC_CHATKIT_API_URL: {{ .Values.configMap.data.NEXT_PUBLIC_API_BASE_URL | quote }}
  NEXT_PUBLIC_CHATKIT_DOMAIN_KEY: {{ .Values.configMap.data.NEXT_PUBLIC_CHATKIT_DOMAIN_KEY | default "todo-web-app-hunain-vercel" | quote }}
  ENVIRONMENT: {{ .Values.configMap.data.ENVIRONMENT | quote }}
  ALLOWED_ORIGINS: {{ .Values.configMap.data.ALLOWED_ORIGINS | quote }}
