apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.commonLabels.app }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.commonLabels.app }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.commonLabels.app }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          envFrom:
            - configMapRef:
                name: todo-app-config
            - secretRef:
                name: {{ .Values.existingSecret }}
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "{{ .Values.configMap.data.NEXT_PUBLIC_API_BASE_URL }}"
          resources:
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
