apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.commonLabels.app }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  CHATKIT_WORKFLOW_ID: {{ .Values.secrets.chatkitWorkflowId | quote }}
