apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.commonLabels.app }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ .Values.commonLabels.app }}
    component: frontend
